# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  mvn_test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: ['8', '11', '13', '15']
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
    name: Test Java ${{ matrix.java }} (${{ matrix.os }})
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-package: 'jdk'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
